{{- range .Values.apps }}
  {{- with . }}
---

apiVersion: v1
kind: Service
metadata: 
  name: {{ .name }}-svc
  labels: 
    app: {{ .name }}-svc
spec: 
  ports: 
  - port: {{ .port }}
    targetPort: {{ .port }}

  type: NodePort
  selector:
    app: {{ .name }}
---
{{- end}}
  {{- end}}